### ISSUE TITLE
TeamSpeak Button

### ISSUE THREAD

**Issue by NATION42** [LaGTeK/Server_Information_Panel#2]
Am I doing something wrong or is it not working?

 "BUTTON1NAME": "TeamSpeak",
    "BUTTON1LINK": "ts3server://FQDN.from.TS3Server",

He should open a browser window / tab with the question
whether to open the teamspeak client.

**Comment by Chi-Yu** [comment]
As far as I can tell, the URL including the `ts3server` protocol is merely passed to DayZ to handle it and `ts3server` doesn't seem to work well.

Good news is: Starting with TeamSpeak version 5 (which is in closed beta at the time of writing), you can use `teamspeak://` instead which appears to work much better.
